// Mapping marque+modèle → titre d'article Wikipedia (anglais)
// Utilisé pour récupérer la photo via l'API REST Wikipedia
const SLUGS = {
  'Renault_Clio':               'Renault_Clio',
  'Renault_Clio E-Tech':        'Renault_Clio',
  'Renault_Megane E-Tech':      'Renault_Mégane_E-Tech',
  'Renault_Austral E-Tech':     'Renault_Austral',
  'Renault_Kadjar':             'Renault_Kadjar',
  'Renault_Zoe':                'Renault_Zoé',
  'Renault_Scenic E-Tech':      'Renault_Scenic_E-Tech',
  'Renault_5 E-Tech':           'Renault_5_(2024)',
  'Renault_4 E-Tech':           'Renault_4_(2024)',
  'Peugeot_208':                'Peugeot_208_(2019)',
  'Peugeot_e-208':              'Peugeot_e-208',
  'Peugeot_308':                'Peugeot_308',
  'Peugeot_e-308':              'Peugeot_308',
  'Peugeot_508':                'Peugeot_508',
  'Peugeot_2008':               'Peugeot_2008',
  'Peugeot_e-2008':             'Peugeot_e-2008',
  'Peugeot_3008 Hybrid':        'Peugeot_3008',
  'Peugeot_e-3008':             'Peugeot_E-3008',
  'Volkswagen_Polo':            'Volkswagen_Polo',
  'Volkswagen_Golf':            'Volkswagen_Golf',
  'Volkswagen_Golf GTE':        'Volkswagen_Golf_GTE',
  'Volkswagen_T-Roc':           'Volkswagen_T-Roc',
  'Volkswagen_Tiguan':          'Volkswagen_Tiguan',
  'Volkswagen_Passat':          'Volkswagen_Passat',
  'Volkswagen_ID.3':            'Volkswagen_ID.3',
  'Volkswagen_ID.7':            'Volkswagen_ID.7',
  'Toyota_Yaris':               'Toyota_Yaris',
  'Toyota_Corolla':             'Toyota_Corolla',
  'Toyota_C-HR':                'Toyota_C-HR',
  'Toyota_C-HR PHEV':           'Toyota_C-HR',
  'Toyota_RAV4 Hybrid':         'Toyota_RAV4',
  'Toyota_Camry Hybrid':        'Toyota_Camry',
  'Toyota_Yaris Cross':         'Toyota_Yaris_Cross',
  'BMW_Série 3':                'BMW_3_Series',
  'BMW_Série 1':                'BMW_1_Series',
  'BMW_i4':                     'BMW_i4',
  'BMW_iX1':                    'BMW_iX1',
  'BMW_X1':                     'BMW_X1',
  'Mercedes-Benz_Classe C':     'Mercedes-Benz_C-Class',
  'Mercedes-Benz_GLC':          'Mercedes-Benz_GLC-Class',
  'Mercedes-Benz_EQA':          'Mercedes-Benz_EQA',
  'Audi_A4':                    'Audi_A4',
  'Audi_Q4 e-tron':             'Audi_Q4_e-tron',
  'Tesla_Model 3':              'Tesla_Model_3',
  'Tesla_Model Y':              'Tesla_Model_Y',
  'Volvo_S60':                  'Volvo_S60',
  'Volvo_XC40 Recharge':        'Volvo_XC40_Recharge',
  'Honda_Civic e:HEV':          'Honda_Civic',
  'Honda_HR-V e:HEV':           'Honda_HR-V',
  'Ford_Focus':                 'Ford_Focus',
  'Ford_Kuga Hybrid':           'Ford_Kuga',
  'Ford_Mustang Mach-E':        'Ford_Mustang_Mach-E',
  'Hyundai_Kona Electric':      'Hyundai_Kona',
  'Hyundai_Ioniq 6':            'Hyundai_IONIQ_6',
  'Hyundai_Ioniq 5':            'Hyundai_IONIQ_5',
  'Hyundai_Tucson Hybrid':      'Hyundai_Tucson',
  'Kia_Niro EV':                'Kia_Niro',
  'Kia_EV6':                    'Kia_EV6',
  'Kia_EV3':                    'Kia_EV3',
  'Kia_Sportage Hybrid':        'Kia_Sportage',
  'Dacia_Duster':               'Dacia_Duster',
  'Dacia_Spring Electric':      'Dacia_Spring',
  'Skoda_Octavia':              'Škoda_Octavia',
  'Skoda_Enyaq':                'Škoda_Enyaq',
  'Skoda_Elroq':                'Škoda_Elroq',
  'Seat_Leon':                  'SEAT_León',
  'Mazda_CX-5':                 'Mazda_CX-5',
  'Nissan_Leaf':                'Nissan_Leaf',
  'Nissan_Ariya':               'Nissan_Ariya',
  'Opel_Corsa':                 'Opel_Corsa',
  'Opel_Corsa Electric':        'Opel_Corsa',
  'Cupra_Born':                 'Cupra_Born',
  'MG_MG4':                     'MG_4_(electric_car)',
  'BYD_Atto 3':                 'BYD_Atto_3',
  'Alfa Romeo_Tonale':          'Alfa_Romeo_Tonale',
  'Alfa Romeo_Tonale PHEV':     'Alfa_Romeo_Tonale',
  'Alfa Romeo_Junior Elettrica':'Alfa_Romeo_Junior',
  'DS Automobiles_DS 4':        'DS_4',
  'Citroën_ë-C4':               'Citroën_ë-C4',
  'Leapmotor_C10':              'Leapmotor_C10',
}

export function getWikiSlug(marque, modele) {
  return SLUGS[`${marque}_${modele}`] ?? `${marque}_${modele}`.replace(/ /g, '_')
}
